title: Jacob's Website
author: Jacob
email: blah-email@youremail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I am making a GitHub Pages Website! ENJOY!!!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
